name: offline_retry_interceptor
description: A robust Dio interceptor that queues failed network requests offline using SQLite and automatically retries them when connectivity is restored.
version: 0.0.1
homepage: https://github.com/fajarcp/offline_retry_interceptor
repository: https://github.com/fajarcp/offline_retry_interceptor
issue_tracker: https://github.com/fajarcp/offline_retry_interceptor/issues

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^7.1.1
  dio: ^5.9.2
  flutter:
    sdk: flutter
  path: ^1.9.1
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  sqflite_common_ffi: ^2.4.0+3